services:
  db:
    image: postgres:16
    container_name: sportilk_db
    environment:
      POSTGRES_DB: sportilk
      POSTGRES_USER: sportik_db
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sportilk -U sportik_db -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  admin:
    build: ./admin
    container_name: sportilk_admin
    ports:
      - "3002:3002"
    restart: unless-stopped
    depends_on:
      - db
  api:
    build: ./api
    container_name: sportilk_api
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: sportilk
      DB_USER: sportik_db
      DB_PASSWORD: root

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  db_data:
