name: Admin Pipeline

on:
  push:
    paths:
      - 'admin/**'
    branches:
      - main
  pull_request:
    paths:
      - 'admin/**'
  workflow_dispatch:

jobs:
  admin-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: admin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Build (optional)
        run: npm run build
