name: API Pipeline

on:
  push:
    paths:
      - 'apps/api/**'
    branches:
      - main
  pull_request:
    paths:
      - 'apps/api/**'
  workflow_dispatch:

jobs:
  api-build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (force)
        run: npm install --force

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Start app (optional – for test only)
        run: npm run start:dev &
